### ISSUE TITLE
eCATT

### ISSUE THREAD

**Issue by tobiashofmann** [tobiashofmann/sap-dev-tech-radar#12]
eCATT: extended Computer Aided Test Tool
Commit: 4e8c55d69d3e19b7588d68f88dee195ff6d1e934

**Comment by larshp** [comment]
Would SAP Tosca be the go-to for testing now-a-days?

**Comment by tobiashofmann** [comment]
Maybe, but it is not from SAP, so it is not included in standard and not ootb available to SAP devs. 

Maybe a question is if eCATT is still widely used or being replaced by another tool, therefore not as relevant as it was once? Moving it from USE to HOLD?

**Comment by pokrakam** [comment]
> Maybe, but it **_is not from SAP_**, so it is not included in standard and not ootb available to SAP devs.

Typo? SAP bought Tricentis and [market it](https://www.sap.com/products/technology-platform/enterprise-continuous-testing.html) (most annoyingly also in a recent OpenSAP course). We got it as part of RISE on my last project. It is also integrated with [Cloud ALM](https://help.sap.com/docs/cloud-alm/setup-administration/tricentis-test-automation-for-sap). 

But you're right that it is not something developers have access to by default. SAP have been adding more and more unit testing capabilities (e.g. SQL & CDS mocking). So one could argue that the technical uses of eCATT can be replaced by ABAP Unit and the functional uses by Tricentis and [various UI-based frameworks](https://help.sap.com/docs/UI_ADD-ON_FOR_SAP_NETWEAVER_20/b4b7cba328bc480d9b373c7da9335537/7cdee404cac441888539ed7bfe076e57.html?locale=en-US).

Personally I only use eCATT's data store when there are many scenarios and outcomes to unit test (Pairwise testing FTW!), but that's about it.

**Comment by tobiashofmann** [comment]
Tricentis was bought by SAP? I do not find this news on the [Tricentis press release page](https://www.tricentis.com/news/all-press-releases) nor somehwere else. They do have a strong partnership with SAP and SAP _sells_ their product, therefore the **by** in SAP Enterprise Continuous Testing by Tricentis. AFAIK this is like an endorsed business solution for testing. Like SAP did with HP Quality Center. 

Even when SAP sells it: I would not count it as a SAP software, specially as it does not come out of the box.

**Comment by tobiashofmann** [comment]
Added in SDTR 2024.6

**Comment by pokrakam** [comment]
OK I checked back and you're right, SAP didn't buy them outright but they have some kind of an agreement. Tricentis Test Automation is available "out of the box" with SAP Enterprise Support. Further Tricentis products are available at additional license fees from SAP. 
They diverted into a bit of a sales pitch in the OpenSAP DevOps course, and since it was all provided by SAP I had misremembered it. Here's one of the slides: 
<img width="1384" alt="image" src="https://github.com/tobiashofmann/sap-dev-tech-radar/assets/25539927/14a88b6d-0f25-4ae1-b905-be0561911a1b">

It's in Week 4 of OpenSAP DevOps course https://open.sap.com/courses/devops1
